tryDjango/articles/urls.py
from django.urls import path
from .views import (article_search_view,article_create_view,article_detail_view)
app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name= "search"),
    path('create/', article_create_view,name="create"),
    path('<slug:slug>/', article_detail_view,name="detail"),
    
]

tryDjango/recipes/urls.py
from django.urls import path
from .views import (
    recipe_list_view, 
    recipe_create_view,
    recipe_detail_view,
    recipe_update_view,
)
app_name = 'recipes' #recipes:list
urlpatterns =[
    path("", recipe_list_view, name = 'list'),
    path("create/", recipe_create_view, name = 'create'),
    path("<int:id>/edit/", recipe_update_view, name = 'update'),
    path("<int:id>/", recipe_detail_view, name = 'detail'),
]

tryDjango/tryDjango/urls.py
from django.contrib import admin
from django.urls import path , include
from .views import home
from accounts.views import (login_view,logout_view,register_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('', home),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

tryDjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello World</h1>
    <form action="/articles" method="get">
        <input type="text" name="q"/>
        <input type="submit">
    </form>
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>

tryDjango/templates/home.html
{% extends 'base.html' %}

{% block content %}
    
<h1><a href="{%url 'articles:create'%}">Create Article</a></h1>

<!-- <p>{{mylist_str}}</p> -->
{% for x in object_list%}
    {% if x.title%}
    <li><a href="{{x.get_absolute_url}}">{{x.title}} - {{x.content}}</a></li>
    <!-- <li><a href="/articles/{{x.slug}}">{{x.title}} - {{x.content}} - {{x.slug}}</a></li> -->
    {%endif%}
{%endfor%}

{% endblock content %}